### PR TITLE
Collecting errors from required files recursively

### PR DESCRIPTION
**Pull request by kipras**

### CODE REVIEW

**Comment by kipras** [comment]
Closing this for now, because:
* need to add the filenames (where the errors were found) together with the errors, right now error messages show the filename of the initial file
* and also need to add test coverage

I'll reopen once these will be done.

**Comment by hishamhm** [comment]
@kipras either approach for storing errors would work fine (adding a `filename` field, or turning `errors` into a `{string:{Error}}` (isn't it cool we have types to talk about tables like these? :smile: )

**Comment by kipras** [comment]
Added `.filename` to `ParseError`, `Error`, `Unknown`, and added test coverage.

**Comment by hishamhm** [comment]
@kipras LGTM! Merged, thanks!!

**Pull request merged**
